#spring:
#    application:
#        name: shared-config
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://git.oschina.net/geek_qi/AG-Config.git

# 激活本地配置
spring:
    profiles:
        active: native

server:
    port: 8750 #启动端口
