spring:
    application:
        name: shared-monitor

server:
    port: 8764 #启动端口

security:
    user:
        name: whb
        password: 123456
        role: USER
eureka:
     instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/